### ISSUE TITLE
Cram doesn't work on Windows

### ISSUE THREAD

**Issue by AlexeySanko** [brodie/cram#15]
1) doesn't provide entry point for windows
If run trough Python with cmd.exe shell
```
import sys
import cram
args = ['-E', '--verbose', 'src/cmdlinetest\\test_help.t', 'src/cmdlinetest\\test_no_build.py.t', '--shell', 'cmd.exe']
sys.exit(cram.main(args))
```
2) fails with error _main.py: "TypeError: environment can only contain string"
3) fails with error _test.py: "ValueError: invalid literal for int() with base 10: '$?'"

**Comment by AlexeySanko** [comment]
First of all if You have installed cram You can create cram.exe manually:
1) copy script/cram file as cram_,py
2) install pyinstaller (pip install pyinstaller)
3) call pyinstaller.exe --clean --onefile cram_.py
In folder ./dist You'll get cram_.exe file which could be renamed to cram.exe and moved to scripts folder

**Comment by AlexeySanko** [comment]
Created [pull request](https://github.com/brodie/cram/pull/16)

**Comment by AlexeySanko** [comment]
I decreased --fail-under parameter to 98 for passing checks. On the one hand we cannot cover Windows specific code into Linux. On the other hand it looks like not very great. Do You have any idea how to support miltyOS python code?

**Comment by donofthenorth** [comment]
Hi, is this still being maintained? I ran into this issue a few days ago and I tried to make a way around it to no avail.
C:\Program Files (x86)\Python36-32\Scripts>python cram
shell not found: /bin/sh

First I tried to create a copy named, cram.py, but got into the error related to this issue.
C:\Program Files (x86)\Python36-32\Scripts>cp cram cram.py

lsf10 - C:\Program Files (x86)\Python36-32\Scripts>ls
cram                  cram.py               cram_dev.py
easy_install-3.6.exe  easy_install.exe      pip.exe
pip3.6.exe            pip3.exe              __pycache__


lsf10 - C:\Program Files (x86)\Python36-32\Scripts>cram
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\Scripts\cram.py", line 4, in <module>
    import cram
  File "C:\Program Files (x86)\Python36-32\Scripts\cram.py", line 7, in <module>
    sys.exit(cram.main(sys.argv[1:]))
AttributeError: module 'cram' has no attribute 'main'

**Comment by AlexeySanko** [comment]
Hi, @donofthenorth.
No. I closed pull request because now Windows has shell.
Check please this comment - https://github.com/brodie/cram/pull/16#issuecomment-297539307
