### ISSUE TITLE
continuous-integration/appveyor/pr check always fails

### ISSUE THREAD

**Issue by AlexeySanko** [brodie/cram#17]
Build started
git clone -q https://github.com/brodie/cram.git C:\projects\cram
git fetch -q origin +refs/pull/16/merge:
git checkout -qf FETCH_HEAD
Specify a project or solution file. The directory does not contain a project or solution file.

https://ci.appveyor.com/project/brodie/cram/build/1.0.18#L1

**Comment by brodie** [comment]
Going to revisit this later.
