### ISSUE TITLE
Windows compatability problem.

### ISSUE THREAD

**Issue by pahaz** [brodie/cram#2]
Hi. The problem in using `distutils`. 

See this question http://stackoverflow.com/q/1829524/941020 and this answer http://stackoverflow.com/a/1936850/941020

For fix this issuse you need to use `setuptools` as recomended in [Packaging Tool Recommendations](https://packaging.python.org/en/latest/current.html#packaging-tool-recommendations)

**Comment by brodie** [comment]
Can you confirm if this is still an issue? According to http://bugs.python.org/issue3561, this should be fixed in Python 2.7.7 and Python 3.3.0 if you tell the installer to add Python to the PATH.
