### ISSUE TITLE
BrokenPipeError when piping cram to head

### ISSUE THREAD

**Issue by yaccz** [brodie/cram#27]
```
yac@remy % cat foo.t
  $ for i in {0..20}; do echo "y"; done
--------------------------------------------------------------------------------
~
yac@remy % cram foo.t | head -n 1
!
Traceback (most recent call last):
  File "/usr/bin/cram", line 7, in <module>
    sys.exit(cram.main(sys.argv[1:]))
  File "/usr/lib/python3.6/site-packages/cram/_main.py", line 195, in main
    for path, test in tests:
  File "/usr/lib/python3.6/site-packages/cram/_cli.py", line 132, in runcli
    _log('\n', None, verbose)
  File "/usr/lib/python3.6/site-packages/cram/_cli.py", line 50, in _log
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by pjeby** [comment]
FWIW, I was able to fix this in my local install by adding these lines to the end of `cram/__main__.py`:

```python
except IOError as e:
    if e.errno != errno.EPIPE:
        raise
```

**Comment by yaccz** [comment]
Makes sense. I have recently encountered similar problem but in shell where I had to wrap my pipeline in sigpipe handler like

     sigpipe cat $file | tee foo

where sigpipe:

     function sigpipe {
       local rc
       $@ || {
         rc=$?
         test $rc -eq 141 ||
           test $rc -eq 0 ||
           fatal "failed with unexpected exitcode: $@"
       }
     }

So I think, @pjeby, your patch is correct solution. Though I suspect newer pythons might provide a subtype of IOError for the errno.EPIPE.

**Comment by roman-neuhauser** [comment]
Dram (https://git.sr.ht/~rne/dram) does not have this bug.
