### ISSUE TITLE
feature request: please add TAP/junit output (or filter to transform)

### ISSUE THREAD

**Issue by branislav-zahradnik-gdc** [brodie/cram#34]
When using this in CI jobs with lot of tests it will be good to have an integration that reports test results a way CI tool understands (eg: jenkins understands junit or has tap plugin)

I personally consider TAP output more human-readable than junit.

**Comment by roman-neuhauser** [comment]
Hello @branislav-zahradnik-gdc , long time no see.

I'm confused by this PR since cram has had `--xunit-file` since ages, we used it in GD when I worked there and Jenkins had no problem with the outputs IIRC.

What is this actually about?
