### ISSUE TITLE
Spwaning a daemon hangs the test suite

### ISSUE THREAD

**Issue by prologic** [brodie/cram#6]
So simple little test case so far:

``tests/udns.t``:
```
#!cram
    $ udnsd -d -b 127.0.0.1:5300 --dbhost $(docker-machine ip dev) --pidfile $TEMP/udnsd.pid
    [0]

    $ kill $(cat $TEMP/udnsd.pid)
    [0]
```

I'm trying to use [cram](https://bitheap.org/cram/) to write a bunch of integration tests for [udns](https://github.com/prologic/udns) which initially require me to spin up a redis server, the udnsd daemon then run a bunch of ``udnsc`` and ``dig`` commands verifying expected output.

**Comment by prologic** [comment]
When I run this I get:
```#!bash
(udns)
prologic@MacBook-Pro
Sat Jan 09 18:06:02
~/tmp/udns
 (master) 0
$ cram tests
tests/udns.t: ^CTraceback (most recent call last):
  File "/Users/prologic/.virtualenvs/udns/bin/cram", line 4, in <module>
    sys.exit(cram.main(sys.argv[1:]))
  File "/Users/prologic/.virtualenvs/udns/lib/python2.7/site-packages/cram.py", line 505, in main
    patchcmd, answer, opts.indent)
  File "/Users/prologic/.virtualenvs/udns/lib/python2.7/site-packages/cram.py", line 322, in run
    refout, postout, diff = test(abspath, shell, indent)
  File "/Users/prologic/.virtualenvs/udns/lib/python2.7/site-packages/cram.py", line 202, in test
    output = p.communicate(input=''.join(stdin))[0]
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 799, in communicate
    return self._communicate(input)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1411, in _communicate
    stdout, stderr = self._communicate_with_select(input)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1512, in _communicate_with_select
    rlist, wlist, xlist = select.select(read_set, write_set, [])
KeyboardInterrupt
```

The very first invocation doesn't terminate properly and give the expected exit status. By hand however:
```#!bash
$ udnsd -d -b 127.0.0.1:5300 --dbhost $(dm ip dev)
2016-01-09 18:01:35,705 - udns.server - INFO - DNS Server Ready! Listening on 127.0.0.1:5300
```

which exits cleanly and daemonizes and I can later terminate it:
```#!bash
$ pgrep -f udns
17743
$ kill 17743
```

**Comment by brodie** [comment]
Thanks for trying out Cram!

Your application isn't closing all open file descriptors after daemonizing. When Cram runs `/bin/sh`, it sets up a pipe for `stdout` (so it can read the output of the shell script). `udnsd` inherits `stdout`, writes the startup message, but doesn't close it after daemonizing. Because it isn't fully closed, Cram waits indefinitely for more script output (it's calling `select()` with the pipe's read `fd` which never returns after the startup message).

In the circuits library that's doing the daemonizing, something like this might work:

```diff
--- app/daemon.py.old	2016-01-17 01:11:29.000000000 -0800
+++ app/daemon.py	2016-01-17 01:39:26.000000000 -0800
@@ -14,6 +14,8 @@
 from os.path import isabs
 from sys import stderr, stdin, stdout
 from os import _exit, chdir, dup2, setsid, fork, getpid, remove, umask
+from os import closerange
+from resource import getrlimit, RLIM_INFINITY, RLIMIT_NOFILE
 
 
 from circuits.core import handler, Component, Event
@@ -115,6 +117,12 @@
         stdout.flush()
         stderr.flush()
 
+        maxfd = getrlimit(RLIMIT_NOFILE)[1]
+        if maxfd == RLIM_INFINITY:
+            maxfd = 2048
+
+        closerange(0, maxfd)
+
         si = open(self.stdin, "r")
         so = open(self.stdout, "a+")
         se = open(self.stderr, "a+")
```

It's possible Cram could do something smarter to work around this situation, but I'm not sure what it is. The `select()` call I mentioned is happening inside the `subprocess` library, so it might be hard to change the behavior there. But I'm not sure if there's anything I can do about it regardless. I'm open to suggestions if you have any ideas.

**Comment by prologic** [comment]
You know... You are awesome! I did not expect you to look into this quite
as deep as you have done! Thank you! A little context I think is in order;
whilst circuits is a great eventing and component framework; lots of code
that make up its library of components were "borrowed". I in fact looked at
``circuits/app/daemon.py`` just a few months ago with this exact problem I
believe and started comparing its internal implementation to other
"daemoniation" libraries/tools to compare "correct behaviour".

I'll try your suggestion out and reference this issue in closing (*assuming
it works*); Thank you :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au
